name: Deploy Website

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Run Development Server
      run: pnpm run dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Deploy
      run: pnpm run deploy  # Replace with your actual deployment command
